### ISSUE TITLE
Compatibility check finds something that doesn’t exist in my project

### ISSUE THREAD

**Issue by 6nv** [grafana/levitate#380]
Ref: https://community.grafana.com/t/compatibility-check-finds-something-that-doesnt-exist-in-my-project/111182

---

Hi all, I'm getting an [error](https://github.com/nicfv/Psychart/actions/runs/7398043595/job/20126338962#step:6:22) in my compatibility check workflow that is not part of my project:

```
1) Changed `PanelPlugin.setPanelOptions` used in `src/module.ts:267`
Parameter type changed:

+ Added - Removed

-declare type PanelOptionsSupplier<TOptions> = (builder: PanelOptionsEditorBuilder<TOptions>, context: StandardEditorContext<TOptions>) => void;
+type PanelOptionsSupplier<TOptions> = (builder: PanelOptionsEditorBuilder<TOptions>, context: StandardEditorContext<TOptions>) => void;
```

First of all, my [`module.ts`](https://github.com/nicfv/Psychart/blob/ce5c93299fac92de286d3db728d2bf62648033cb/src/module.ts#L1) file is only 266 lines, and I also searched for "PanelOptionsSupplier" and it is not anywhere in my file. I also found a GitHub [issue](https://github.com/grafana/levitate/issues/231) that may be loosely related. Other than that, I'm stuck. Can someone help me track this down please?

**Comment by sympatheticmoose** [comment]
@academo was there any update to this issue?
