### ISSUE TITLE
Levitate: move to ESM

### ISSUE THREAD

**Issue by leventebalogh** [grafana/levitate#393]
Related: https://github.com/grafana/plugin-tools/issues/654

### The problem
We have dependencies in the project (e.g. ora and execa) which we cannot update to because they are ESM only packages and current build tooling doesn't support them.

### Possible solution
Build Levitate as an ESM package. (It shouldn't be a breaking change for node LTS).

**Comment by tolzhabayev** [comment]
Can you add more as to what and why, do we expect someone who is using it to change anything ([e.g.](https://github.com/grafana/grafana/blob/main/scripts/check-breaking-changes.sh#L35))? @leventebalogh

**Comment by leventebalogh** [comment]
Sure thing @tolzhabayev, good point!

I think in Grafana we are using Node v20, so it shouldn't be an issue. Regarding support I think it's fine to support the same node versions as `@grafana/plugin-tools` - however I will check where else levitate is used in our ecosystem to see if we don't break anything.
